simple_marker_detector:
  ros__parameters:
    range:
      hue:
        min: 50
        max: 90
      saturation:
        min: 150
        max: 255
      value:
        min: 150
        max: 255
    visualise: true
    use_sim_time: false
